### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [jdlehman/react-memory-game#1]
Hi Jonathan, thanks for example. One question.

Here you init lock variable inside state
https://github.com/jdlehman/react-memory-game/blob/master/src/components/Game.js#L39

But since setState is not synchronous
http://stackoverflow.com/a/30783011

Don't you think this check
https://github.com/jdlehman/react-memory-game/blob/master/src/components/Game.js#L33
might not work properly?
e.g. user might still be able to bypass it? (even though inside setState you indicated to set lock to true)

**Comment by jdlehman** [comment]
As a first note, this is an example repo I wrote a few years ago that I am not actively updating or maintaining so I am sure it could use some refactoring as my thinking and React knowledge have progressed since this was written. With that said I will try to answer your question.

While `setState` is asynchronous, the state should be set by the time the check is done because it will occur in a later tick in the JS event loop (the user will have to click again to trigger this check again, which would be on a later tick). (which always reminds me of this great [talk on the event loop](https://www.youtube.com/watch?v=8aGhZQkoFbQ)). You are right to look at `setState` usage critically because it is good to always remember that `setState` is async, and multiple `setState` calls will be batched.

The usual case where people can have issues with `setState`'s async nature is when they try to use the state in the same function in which they set it.

For example, the following would not always work:
```js
handleClick() {
  this.setState({lock: true});
  // lock will not necessarily be true in the if statement because setState is async
  if (this.state.lock) {
  }
}
```

There are a few ways this can be solved in the case you have to use state in the same function (and tick of the JS event loop), where it may or may not be updated.

1. You can store the new state in a local variable. This works in most cases, but might also have issues if you are setting the state elsewhere AND if you always want to use the most up to date state. (think if you had a `setInterval` setting the lock state randomly ever few seconds)
```js
handleClick() {
  const newLockState = true;
  this.setState({lock: newLockState});
  if (newLockState) {
  }
}
```

2. Use another form of `setState`: `setState(newStateObj, callback)`

```js
handleClick() {
  this.setState({lock: true}, function() {
   // this callback is called AFTER the state is set
   // this.state.lock will be true
  });
}
```

The other issue people often have with `setState`'s async nature is when they use the current state to set the next state. In the example of a counter:

```js
  // this might have problems because setState batches calls
  // so if multiple of the following calls were batched together (let's say 3 of them)
  // it would only increment by 1 instead of 3
  this.setState({counter: this.state.counter + 1})
```

This can be solved by using the updater function form of `setState`:
```js
  this.setState(function(prevState, props) {
    // this will work correctly with setState batching
    return {counter: prevState.counter + 1};
  });
```

Check out the [`setState` docs](https://facebook.github.io/react/docs/react-component.html#setstate) for more details.

Going back to the code in this example, it would probably be better to put the code following: https://github.com/jdlehman/react-memory-game/blob/master/src/components/Game.js#L39 (where lock is initially set to true and the selected card is flipped), in a callback to that `setState` call:

```js
this.setState({cards, locked: true}, function() {
    if (this.state.lastCard) {
   // ...
   }
});
```
